### PR TITLE
add staged data locations to setup experiment.

### PR DESCRIPTION
**Pull request by delippi**

### CODE REVIEW

**Comment by delippi** [comment]
@guoqing-noaa, It works after the latest commit. The link paths that I had in setup experiment weren't working right.

**Comment by guoqing-noaa** [comment]
@delippi Thanks! So I can go ahead to merge?

**Comment by delippi** [comment]
Yeah, I think it is good to go now.

**Comment by guoqing-noaa** [comment]
Thanks!

**Pull request merged**
